### ISSUE TITLE
RPC instead of client / server design

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#29]
**Is your feature request related to a problem? Please describe.**
Current architecture for Lachesis to EVM interaction is client server design.

A Lachesis nodes specifies a downstream client. An EVM node exposes a proxy server to receive responses. 

This design tightly couples a Lachesis node with an EVM node. The design is supposed to allow for join/drop participation. So a Lachesis node can not have awareness of an EVM node. Although EVM nodes should have awareness of Lachesis nodes.

**Describe the solution you'd like**
New EVM joins

The EVM genesis file creates a stateHash. This hash must be sent to the Lachesis node. This stateHash is used to see which blockstream is appropriate. The node needs to go into FastSync mode and synchronize missing blocks until the state matches.

From here nodes can either subscribe to WS for blocks, or simply use incremental catchup calls with their attached node. Alternatively block propagation could occur via standard gossip based communication protocols and the lachesis network needs to keep track of the evm network.

**Comment by RoanBrand** [comment]
Just to be clear:

- Many EVMs will be able to join a single node.
- When do you want the evm to send the stateHash to the node as you mention: Is this the same stateHash the node currently receives from rpc calls to the EVM `State.CommitBlock` ? If so, doesn't that only happen when the node syncs with the EVM?

**Comment by RoanBrand** [comment]
@andrecronje 

I see the current stateHash isn't being used by the node: https://github.com/andrecronje/lachesis/commit/06bbb032bffbbf1346770b04f2ac5b18b45dcff3#diff-fe72219e854ef7d912a53b4f7dea56afL604

Will the stateHash only be sent from an EVM once at first connect? Or each time the node sends a block (commit block)?

If the statehash is not needed when sending blocks it would be quite trivial to finish the websocket subscribe model where the node would just send out blocks to each currently connected EVM.

The problem comes in where the EVM needs to send back an associated stateHash with a received block.  This is a request-response model that is more suited for rpc. (the node would need extra layer of logic to distinguish between incoming tx's and statehashes, etc. And it would need to keep track of which hash for which block previously sent)

If you want to use 1 connection between a node and evm and want to use websockets we could try something like:
https://github.com/mem/ws-rpc/blob/master/client/main.go

**Comment by RoanBrand** [comment]
@andrecronje 
Minor stuff left:
- Test when client disconnects gracefully from node that node deletes connection
- After WS ping-pong timeout also disconnect and delete.
- VM must retry connecting to node indefinitely if not currently connected
- Remove lachesis node -c flag and the evm -lachesis.client_addr flags

Do you agree with all that?
One thing still unclear: When blocks are sent to VMs, each block send request returns a statehash. What will the consequences/policy be around that?
Currently I return the last client's one.

**Comment by andrecronje** [comment]
We can remove the stateHash logic. 
Agreed on all items.
Are you working on the EVM implementation as well?
