### ISSUE TITLE
Relocate DB - New feature

### ISSUE THREAD

**Issue by niiiro** [Fantom-foundation/go-lachesis#406]
Hello,
It'd be much of a use to have the ability to relocate the DB to another drive.

Many thanks.

**Comment by devintegral3** [comment]
Hi!
Currently you may safely relocate the DB files, by simply moving or coping datadir on another drive:
```shell
mv /path/to/.lachesis /new/path/to/.lachesis
```
By default, lachesis datadir is `$HOME/.lachesis`

It's safe to launch lachesis on a new drive or on a completely new machine, by copying datadir files.
You may launch lachesis with new datadir, by using --datadir flag:
```shell
lachesis --datadir /new/path/to/.lachesis
```

Pay attention that if run a validator, you must not launch multiple instances of the same validator simultaneously - it may lead to doublesign due to race condition between those instances.

If you need to transfer your keys on a new device, then you may safely transfer files from /path/to/.lachesis/keystore on a new device
