### ISSUE TITLE
P2P communication failure for new Lachesis nodes

### ISSUE THREAD

**Issue by rekt0x** [Fantom-foundation/go-lachesis#419]
**Describe the bug**
Lachesis node does not connect to `StaticNodes` as defined in the `mainnet.toml` file or bootstrap connections to any other nodes. So the node does not sync because it has no connections to other nodes.

The node returns with the following error:
```
too many peers
```

It's possible to manually add another node to the `BootstrapNodes` in the `mainnet.toml` file. Then the node will connect to this node and sync the chain. But it stays like that and it's only connected to that single node (which is a serious issue).

**To Reproduce**
1. Follow the guide to setup a lachesis node: https://github.com/Fantom-foundation/lachesis_launch
2. Attach to the lachesis console
3. Enter `admin.peers`

**Expected behavior**
The node should connect to other nodes and sync the chain.

**Comment by sfxdxdev** [comment]
The problem is related to Opera bootnodes configuration. This configuration doesn't use discovery bootnodes, but rather static nodes. According to the response you mentioned, those static nodes have exhausted their connections limit, and as a result they won't accept any new connections.

To configure a discovery node, you have to specify external IP which you want to be advertised in discovery: `--nat=extip:YOUR_IP`.
Also discovery uses UDP, so you'll have to open 5050 UDP port if it's closed on your server (or any other p2p port if it's not default).
Without these steps, you'll find other nodes in discovery, but other nodes won't find you.
After both of those conditions are true, the node may be used as a discovery node.

From your side, you may setup a discovery node, and then when Opera bootnodes configuration is resolved, your node will participate in discovery and hence will improve the connectivity of the network. Until then, you may use your own discovery node as a bootnode. To do that, add into your config file (add BootstrapNodesV5 under [Node.P2P] section):
```
[Node.P2P]
BootstrapNodesV5 = ["enode://verylonghex@33.44.55.66:5050"]
```

**Comment by rekt0x** [comment]
By Opera bootnodes configuration you mean an issue in the code, right?

What are those parameters related to?
```
--bootnodes value                    Comma separated enode URLs for P2P discovery bootstrap (set v4+v5 instead for light servers)
--bootnodesv4 value                  Comma separated enode URLs for P2P v4 discovery bootstrap (light server, full nodes)
--bootnodesv5 value                  Comma separated enode URLs for P2P v5 discovery bootstrap (light server, light nodes)
```

Seems like the difference is light server/node vs full server/node. What's the difference?

In the `mainnet.toml` config file there are these parameters:
```
...

[Node.P2P]
[...]
NoDiscovery = false
DiscoveryV5 = true

...
```

What are those for? Seems like `DiscoveryV5` enables the node to be discovered by others. Not sure about `NoDiscovery`.

When you say using my own discovery node as my boot node, are you talking about 2 separate machines? Or is a single node using the discovery service of itself?

**Comment by sfxdxdev** [comment]
> By Opera bootnodes configuration you mean an issue in the code, right?

The issue is absence of bootnodes in Opera mainnet.toml.
It can be fixed by updating mainnet.toml, without updating go-lachesis executable.

> Seems like the difference is light server/node vs full server/node. What's the difference?

There's no difference really, because there's no light nodes yet. The description has to be fixed. Discovery V5 does work for full nodes (it's the only type of node we have currently).

> What are those for? Seems like DiscoveryV5 enables the node to be discovered by others. Not sure about NoDiscovery. Are they the same as the parameters for the Lachesis binary?

`NoDiscovery = false` specifies that discovery isn't disabled. `DiscoveryV5 = true` specifies that discovery v5 is enabled (in addition to discovery v4).
"Discovery is enabled" means:
- Your node will search for other nodes in discovery network
- If you specified `--nat=extip:YOUR_IP`, then your IP will be advertised in discovery network 

> What are those for? Seems like DiscoveryV5 enables the node to be discovered by others. Not sure about NoDiscovery. Are they the same as the parameters for the Lachesis binary?

Yes, those are flag versions of config fields `NoDiscovery` and `DiscoveryV5`

You can check it by running `lachesis --nodiscover dumpconfig`, `lachesis dumpconfig` and comparing the output. `dumpconfig` is a command to return the final config, after all keys are applied.

> When you say using my own discovery node as my boot node, are you talking about 2 separate machines? Or is a single node using the discovery service of itself?

Single node does use discovery service of itself, but if there's no discovery nodes - then there's peers to be found. Since Opera mainnet doesn't offer official discovery nodes right now, the only way to use discovery is to either setup your own bootnode, or find community bootnodes.

Usage of static nodes is still an option for you, but ensure you use as many static connections as possible.

**Comment by quan8** [comment]
@rekt0x ok to close this issue?

**Comment by rekt0x** [comment]
@quan8 yes, can be closed.
